/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef thrift_file_CONSTANTS_H
#define thrift_file_CONSTANTS_H

#include "thrift_file_types.h"

namespace ThriftTest {

class thrift_fileConstants {
 public:
  thrift_fileConstants();

};

extern const thrift_fileConstants g_thrift_file_constants;

} // namespace

#endif
