// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MyService.h"
#include "myclientapplication.h"
using namespace ::ZTE;
// Random string
int main(int argc, char* argv[])
{
    MyClientApplication myApp;
    return myApp.run(argc, argv);
}
