/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thrift_file_constants.h"

namespace ZTE {

const thrift_fileConstants g_thrift_file_constants;

thrift_fileConstants::thrift_fileConstants() {
}

} // namespace

